box_office/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views # 이메일로 비밀번호 재설정의 위한 import
# from restFrameWork import views
# from  restFrameWork import views 

# # 5-1. RestTemplate and FASTAPI
# from django.contrib.auth.models import User # Django를 Client를 만들기위한, api-auth를 위한 Django 내장 User 객체 import하기 
# from rest_framework import routers, serializers, viewsets   # 먼지는 모르겠지만 Django REST framework 사이트를 따라가면서 import하기

# # 5-2. Serializers define the API representation # import한 Serializers 모듈로 API대표자대리인표현을 정의하기
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         Model = User
#         fields = ['url', 'username', 'email', 'is_staff']

# # 5-3. ViewSets 모듈로 view의 behavior을 정의하기
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer

# # 5-4. Routers가 자동으로 쉽게 환경설정배열(configuration) 결정할수 있도록 제공한다
# router = routers.DefaultRouter()
# router.register(r'users', views.UserViewSet)   #처음보는것 f''String같은거  r'' -> RawString ESCAPE문법을 ESCAPE하지못하도록 제어
# router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', TemplateView.as_view(template_name='common/home.html'), name='home'),
    path("movie/", include("movie.urls")),
    path("user/", include("user.urls")),
    # path('password/', include('django.contrib.auth.urls')),

    # 비밀번호 재설정 토큰관련 url
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),

    # api-auth RestTemplate를 위한 root url 설정
    # 6. 우리의 API객체를 자동으로 URL을 전달하고, 우리는 추가적으로 브라우저 API를 위한 로그인 URL들을 include
    # path('api-auth/', include('restFrameWork.urls', namespace='restFrameWork')),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

movie/urls.py
from django.urls import path
from . import views
app_name = 'movie'
urlpatterns = [
    
    path('board/1', views.MovieBoardtest1.as_view(), name='board1'),
    path('board/1to2/', views.director_to_genre, name='board1to2'),
    path('board/2', views.MovieBoardGenre.as_view(), name='board2'),
    path('board/2to3/', views.genre_to_actor, name='board2to3'),
    path('board/3', views.MovieBoardActor.as_view(), name='board3'),
    path('board/3to4/', views.actor_to_nations_opendt_audit, name='board3to4'),
    path('board/4',views.MovieBoardtest ,name='board4'),

    path('board/board4toresult', views.nations_opendt_audit_to_result, name='board4toresult'), ##원래 사용하는 함수뷰
    # path('select/',views.SelectCreateView.as_view(), name='select'),
    # path('board/board4toresult', views.NationsOpendtAuditToResult.as_view(), name='board4toresult'),  ## 시도중인 클래스뷰
        ## class뷰에 generic.ListView를 상속받아 저장되어있는 세션을 이용한 쿼리문 작성을 시도하였으나,
        ## class뷰에는 함수형뷰의 request 매개변수가 없어서 request인수에서 session을 불러오는게 어려워보인다.
        ## class view django session으로 구글에 검색시 맨 처음 나오는 영어질문에 답이 있는것 같으나, override가 복잡하고 이해하지 못해서 작업중지한 상황.
    
    path('board/1/S/', views.movieboardselectview, name= 'board1S'),  
        ## 함수형뷰 테스트였었던 url로 session들을 뽑아낼 result 결과페이지를 연결하는 url

    # 자료실에서 결과보기를 누르면 이동하는 url
    path('board/2/S/<int:pk>', views.movieboardputview.as_view(), name='board2S'),
    
    # 자료실에서 삭제버튼을 누르면 이동하는 url
    path('board/2/S/<int:pk>/delete', views.delete_board, name='delete'),

    # 영화 추천 페이지 url
    path('recommendation/', views.recommendation.as_view(), name='recommendation'),
    # 영화 추천 페이지 검색 자동완성 경우 url
    path('recommendation/autofind/', views.recomAjax, name='recomajax'),
    ####### 기준선으로 위 urlpattern은 사용 / 아래 urlpattern은 비사용 ###########

    # path('board/',views.MovieBoard ,name='board'), 
    # path('select/', views.select, name='select'),
    # path('select/',views.SelectCreateView.as_view(), name='select'),
    # path('selectlist/', views.SelectListView.as_view(), name='selectlist'),
    # path('selectdetail/', views.SelectDetailView.as_view(), name='selectdetail'),
    # path('<int:user_id>/board/1/S', views.MovieBoard1SelectCreateView.as_view(), name= 'board1S'), ## 클래스뷰로하려는안되서 함수형뷰사용해보려함.
    # path('<int:movie_id>/board/1/S', views.MovieBoard1SelectDetailView.as_view(), name= 'board1S'),
    
]

user/urls.py
from django.urls import path
from . import views
# from user.views import kakaoSignInView, kakaoCallbackView
from django.contrib.auth import views as auth_views
from rest_framework_simplejwt.views import TokenRefreshView
app_name = 'user'
urlpatterns = [
    # path('login/',auth_views.LoginView.as_view(template_name = 'dist/index.html', next_page = 'movie:board1'),name='login'),
        # django.contrib.auth.views를 import하여 내장 LoginView를 사용하는 url
        # dist/index.html은 로그인기능과 회원가입기능이 같이있는 템플릿
    path('join/', views.UserCreateForm.as_view(),name='join'),
        # 회원가입기능의 ClassView와 관련된 url
    # path('join/', views.UserCreateForm.as_view(),name='join'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('login/',auth_views.LoginView.as_view(template_name = 'dist/index.html', next_page = '/'),name='login'), 
    # path('login/', views.LoginClassView.as_view(), name='login'),

    path('logout/',auth_views.LogoutView.as_view(next_page = '/'),name='logout'),
        # django.contrib.auth.views를 import하여 내장 LogoutView를 사용하는 url
        # 로그아웃 후 이전페이지인 / 로 이동

    path('profile/', views.profile, name='profile'),
        # 프로파일페이지와 관련된 뷰와 연결해주는 url
    path('profile/selected/', views.UserSelectedDataView.as_view(), name='selected_data'),
    
    path('delete_user_page/', views.delete_user_page, name='delete_user_page'),
        # 회원탈퇴페이지와 관련된 뷰와 연결해주는 url
    path('delete_user/', views.delete_user, name='delete_user'),
        # 새로이 만들고자하는 회원탈퇴url

    path('password_check_ajax/', views.password_check_ajax, name='password_check_ajax'),
    # 비밀번호 변경시 현재의 비밀번호와 동일한 비밀번호로 변경하지 못하도록 하는 비밀번호 체크 ajax 함수

    path('change_user_page/', views.userchangepage ,name='change_user_page'),
        # 회원정보수정페이지와 관련된 뷰와 연결해주는 url
    path('change_user/', views.userchangeview ,name='change_user'),
    # path('<int:auth_user_id>/change_user/', views.userchangeview ,name='change_user'),
        # 회원정보수정기능과 관련된 뷰와 연결해주는 url
    
    path('ajax_user_login/', views.ajax_user_login, name='ajax_user_login'),
        # 로그인 관련 ajax view함수  

    path('ajax_user_signup/', views.ajax_user_signup, name='ajax_user_signup'),
        # 회원가입 관련 ajax view함수

    ####### 주석기준 위 url 사용중인 url / 아래 비사용 혹은 테스트중인 url
    
    # 
    # path('constitution_email/', views.constitution_email, name='constitution_email'),
        # 영화사 이메일 등록관련 view함수

    path('ajax_confirm_email/', views.ajax_confirm_email, name='ajax_confirm_email'),
        # 영화사 이메일 확인관련 ajax view함수

    path('delete_user/', views.delete_user, name='delete_user'), ## 원래사용하던 회원탈퇴url
        # 회원탈퇴기능과 관련된 뷰와 연결해주는 url
    # path('login/', views.LoginClassView.as_view(), name='login'),

    #######
    # 비밀번호 재설정 토큰관련 url
    path('password_reset/', views.password_reset_request, name="password_reset"),

    # # 원본 이메일 보내기 
    path('ajax_token_email/', views.ajax_token_email, name="ajax_token_email"),

    # # 테스트용 이메일 보내기
    # path('ajax_token_email/', views.AjaxTokenEmail, name='ajax_token_email'),
    #     # 영화사 이메일 확인관련 ajax view함수

    # 이메일에서 클릭하라는 부분 클릭시 데이터를 받아내는 url 그 받은데이터를 activate view에 전달을 한다
    path('activate/<str:uidb64>/<str:token>/<str:targetemail>', views.activate, name="activate"),

    path('ajax_to_find_confirm_email/', views.ajax_to_find_confirm_email, name="ajax_to_find_confirm_email"),


    path('findpasswordreset/', views.findpasswordreset, name="findpasswordreset"),
    path('emailresetpassword/<str:username>/<str:targetemail>', views.emailresetpassword, name="emailresetpassword"),

    
    path('fromeamilpasswordreset/', views.fromeamilpasswordreset, name='fromeamilpasswordreset'),


    path('toresetpasswordfindemail/', views.toresetpasswordfindemail, name='toresetpasswordfindemail'),

    path('toresetpasswordcheckpassword/', views.toresetpasswordcheckpassword, name='toresetpasswordcheckpassword'),
    
    #탈퇴하기 직전 탈퇴의 이유를 가지고 view로 가는 url
    path('delete_user_reason/', views.delete_user_reason, name='delete_user_reason'),


    # 실패
    # 카카오 로그인 요청에 대한 코드 
    # path('login_user_kakao', views.login_user_kakao, name='login_user_kakao'),
    # 다녀오고나서 데이터를 가지고 redirect될 url과 View
    # path('login_user_kakao_callback', kakaoCallbackView.as_view(), name='login_user_kakao_callback'),
    

    
]

movie/models.py
from django.db import models
from django.contrib.auth import models as auth_models
from django.contrib.auth import views as auth_views

class TargetBase(models.Model):
    moviecd = models.IntegerField(db_column='movieCd', primary_key=True)  # Field name made lowercase.
    movienm = models.TextField(db_column='movieNm', blank=True, null=True)  # Field name made lowercase.
    opendt = models.DateTimeField(db_column='openDt', blank=True, null=True)  # Field name made lowercase.
    salesacc = models.BigIntegerField(db_column='salesAcc', blank=True, null=True)  # Field name made lowercase.
    audiacc = models.IntegerField(db_column='audiAcc', blank=True, null=True)  # Field name made lowercase.
    genre = models.TextField(blank=True, null=True)
    director = models.TextField(blank=True, null=True)
    nations = models.TextField(blank=True, null=True)
    actor1 = models.TextField(blank=True, null=True)
    actor2 = models.TextField(blank=True, null=True)
    actor3 = models.TextField(blank=True, null=True)
    audit = models.TextField(blank=True, null=True)

    class Meta:
        managed = True
        # db_table = 'target_base'

class SelectedBase(models.Model):
    director = models.TextField(blank=True, null=True)
    genre = models.TextField(blank=True, null=True)
    nations = models.TextField(blank=True, null=True)
    audit = models.TextField(blank=True, null=True)
    actor1 = models.TextField(blank=True, null=True)
    actor2 = models.TextField(blank=True, null=True)
    actor3 = models.TextField(blank=True, null=True)
    opendt = models.TextField(blank=True, null=True)
    writer = models.ForeignKey(auth_views.UserModel, on_delete=models.CASCADE)


class Actorlist(models.Model):
    actor1 = models.TextField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'actorlist'

class Secondbase(models.Model):
    index = models.BigIntegerField(blank=True, null=True)
    id = models.BigIntegerField(blank=True, primary_key=True)
    release_date = models.TextField(blank=True, null=True)
    title = models.TextField(blank=True, null=True)
    director = models.TextField(blank=True, null=True)
    genres = models.TextField(blank=True, null=True)
    original_language = models.TextField(blank=True, null=True)
    overview = models.TextField(blank=True, null=True)
    popularity = models.FloatField(blank=True, null=True)
    budget = models.BigIntegerField(blank=True, null=True)
    revenue = models.BigIntegerField(blank=True, null=True)
    tagline = models.TextField(blank=True, null=True)
    vote_average = models.FloatField(blank=True, null=True)
    vote_count = models.IntegerField(blank=True, null=True)
    credits = models.TextField(blank=True, null=True)
    keywords = models.TextField(blank=True, null=True)
    poster_path = models.TextField(blank=True, null=True)
    audits = models.TextField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'secondbase'

class Reason(models.Model):
    reason = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        

movie/forms.py
from django import forms
from django.db import models
from .models import SelectedBase

class SelectedBaseForm(forms.ModelForm):
    class Meta:
        model = SelectedBase
        # fields = ['director', 'nations', 'audit']
        fields = ['director']

templates/movie/main1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>일일영화 - 감독 선택 #1</title>

    {% load static %}  
    <!-- 파비콘 이미지 -->
    <link rel="icon" type="image/png" sizes="32x32" href="../../static/film-slate.png">
    <!-- 메뉴바 css -->
    <link rel="stylesheet" href="{% static 'common/home/menubar.css' %}">

    <!-- 검색창 css -->
    <link rel="stylesheet" href="{% static 'movie/select/dselect.css' %}">
    <!-- DB card 선택 css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css"/>
    <link rel="stylesheet" href="{% static 'movie/select/card.css' %}">
    <!-- 페이징 css -->
    <link rel="stylesheet" href="{% static 'user/selected/pselected.css' %}"> 
    
    <!-- DB card 선택 js  -->
    <script src="{% static 'movie/select/card.js' %}"></script>
    <!-- 메인js화면  -->
    <script src="{% static 'movie/select/dselect.js' %}"></script>
    <!-- j쿼리사용 js -->
    <script src="{% static 'jquery.min.js' %}"></script>
  </head>
  <body>
    <input type="hidden" id="csrf_token" value="{{ csrf_token }}">
    <div class="backs">
      <!-- 메뉴바 -->
      <div class=header>
        <a href="/" class="logo" target="blank">
          <img src="{% static 'My project-1.png' %}" alt="일일영화 로고">
        </a>

        <div class="welcom">
        {% if user.is_authenticated %}
        {{ user.username }}님, 환영합니다.<br>
        </div>

        <div class="names">
          <a href="{% url 'user:profile' %}" class="btn"> 회원정보 </a>
          <a href="{% url 'user:logout' %}" class="btn">로그아웃</a>
        {% else %}
        <!-- <a href="{% url 'user:login' %}" class="btn">로그인하기</a> -->
        {% endif %}
        </div> 
      </div>

      <!-- 페이지 설명 창-->
      <div>
      <h1>감독을 선택해주세요</h1>
      </div>

      <!-- 선택한 내용 보여주기 -->
      <div class="show">
        <input class="showSelect" type="text" name="selected_director" id="selected_director" readonly>
      </div>

      <!-- 검색 창-->
      <form id="searchForm" autocomplete="off" class="box">
        <input type="text" name="searchWord" placeholder="{{ searchWord|default:'감독을 검색해주세요'|default_if_none:'' }}" />
      </form>
      
      <!-- DB 선택 테이블 css -->
      <section>
        <div class="content-list">
          <div class="slider">
            {% for list in targetbase_list %}
            <div class="item" onclick="TableDirector(this)">
              {{ list.director }}
            </div>
            {% endfor %}
          </div>
        </div>
      </section>

      <!-- DB 페이징 기능 -->   
      <div class="pagination">
        <!-- DB 이전 페이지 -->
        {% if page_obj.has_previous %}
          <a href="?searchWord={{ searchWord }}&page={{ page_obj.previous_page_number }}" class="page-link">이전</a>
        {% else %}
          <a href="#" class="page-link" tabindex="-1" aria-disabled="true">이전</a>

        {% endif %}

        <!-- DB 페이지 리스트 -->
        {% for page_number in page_obj.paginator.page_range %}
          {% if page_number >= page_obj.number|add:-5 and page_number <= page_obj.number|add:5 %}
            {% if page_number == page_obj.number %}
              <a href="?searchWord={{ searchWord }}&page={{ page_number }}" class="page-link">{{ page_number }}</a>
            {% else %}
              <a href="?searchWord={{ searchWord }}&page={{ page_number }}" class="page-link">{{ page_number }}</a>
            {% endif %}
          {% endif %}
        {% endfor %}

        <!-- DB 다음페이지 -->
        {% if page_obj.has_next %}
          <a href="?searchWord={{ searchWord }}&page={{ page_obj.next_page_number }}" class="page-link">다음</a>
        {% else %}
          <a href="#" tabindex="-1" aria-disabled="true" class="page-link">다음</a>
        {% endif %}
      </div>
  
      <!-- main2.html로 이동 버튼 -->
      <div class="page_1">
        {% comment %} <a href="{% url 'movie:board1' %}" class="page_1_btn">이전(◀)</a> 
        <a href="javascript:void(0);" class="page_first_btn" onclick="nextBtnEmailCheckAjax();">다음(2/4)</a>
        <a href="javascript:void(0);" class="page_1_btn" onclick="selectDataDirector();">다음(2/4)</a>
        {% endcomment %}
        <div class="modalEmailConstitution">
          <button id="modalOpenBtn">이메일등록</button>
          <button id="modalCloseBtn">닫기</button>
          <div id="emailModal">
            
            <input type="text" name="user_email" placeholder="이메일 ID를 입력" id="userEmailId">
            <div style='color: white;' id="to_to_id">@</div>
            <input type="text" name="domain_email" placeholder="이메일 Domain을 입력" id="userEmailDomain">
            <a href="javascript:void(0);" class="film_email_constitution" id="film_email_constitution_id" onclick="emailCheckAjax()" style="color: white; margin: 0;">등록하기</a>  
          </div>
        </div>
        <a href="javascript:void(0);" class="page_1_btn" onclick="nextBtnEmailCheckAjax();">다음(2/4)</a>
      </div>
      
      <!-- 이메일 모달 -->
      {% comment %}
      <div class="page_first_next">
        <button class="page_first_btn" id="only_one_botton" onclick="constitution();">다음(2/4)</button>
        <a href="javascript:void(0);" class="page_first_btn" onclick="selectDataDirector();">다음(2/4)</a>
        <a href="javascript:void(0);" class="page_first_btn" onclick="nextBtnEmailCheckAjax();">다음(2/4)</a>
      </div>

      <!-- 영화설립이메일 모달창 -->
      <button id="modalOpenBtn">이메일등록

      </button>
      <div id="emailModal">

        <!-- 왼쪽 클릭은 2,3 페이지만-->
        <div class="slide_prev_button slide_button"><a href="movie:board1">◀</a></div>
        <!-- 오른쪽 클릭은 1,2,3 페이지만-->
        <!-- 현지점(1페이지)에서 누르면 바로 2페이지로 가는 임시 기능-->
        <div class="slide_next_button slide_button"><a href="{% url 'movie:board2' %}">▶</a></div>

        <ul>
          <button id="modalCloseBtn">닫기</button>
          <li>
            <input type="text" name="user_email" placeholder="이메일 ID를 입력해주세요." id="userEmailId">@<input type="text" name="domain_email" placeholder="이메일 Domain을 입력해주세요." id="userEmailDomain">
            <a href="javascript:void(0);" class="film_email_constitution" id="film_email_constitution_id" onclick="emailCheckAjax()">등록하기</a>
          </li>
        </ul>  
      </div>
      {% endcomment %}
      
      {% comment %}
        
      
      <!--  영화설립이메일 모달창 -->    
      <div class="modalEmailConstitution">
        <button id="modalOpenBtn">이메일등록</button>
        <button id="modalCloseBtn">닫기</button>
        <div id="emailModal">
          
          <input type="text" name="user_email" placeholder="이메일 ID를 입력" id="userEmailId">
          <div style='color: white;' id="to_to_id">@</div>
          <input type="text" name="domain_email" placeholder="이메일 Domain을 입력" id="userEmailDomain">
          <a href="javascript:void(0);" class="film_email_constitution" id="film_email_constitution_id" onclick="emailCheckAjax()" style="color: white; margin: 0;">등록하기</a>  
        </div>
      </div>
      {% endcomment %}
      
    </div>
  </body>
</html>

<form action="{% url 'movie:board1to2' %}" method="get" id="selectedDirectorForm">
  <input type="hidden" name="director" id="selected_director_hidden_input">
</form>

{% comment %}
<!-- <form action="{% url 'user:constitution_email' %}" method="post" id="film_email_constitution_form_id">
  {% csrf_token %}
  <input type="hidden" name="emailname" id="emailname_input">
  <input type="hidden" name="emaildomain" id="emaildomain_input">
</form> -->
{% endcomment %}

<form action="{% url 'user:ajax_token_email' %}" method="post" id="tokenEmailFromId">
  {% csrf_token %}
  <input type="hidden" name="tokenemailname" id="tokenEmailName">
  <input type="hidden" name="tokenemaildomain" id="tokenEmailDomain">
</form>

templates/movie/main2.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>일일영화 - 장르 선택 #2</title>

  {% load static %}
  <!-- 파비콘 이미지 -->
  <link rel="icon" type="image/png" sizes="32x32" href="../../static/film-slate.png">
  <!-- 메뉴바 css -->
  <link rel="stylesheet" href="{% static 'common/home/menubar.css' %}">

  <!-- 검색창 css -->
  <link rel="stylesheet" href="{% static 'movie/select/dselect.css' %}">
  <!-- DB card 선택 css -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css"/>
  <link rel="stylesheet" href="{% static 'movie/select/card.css' %}">
  <!-- 페이징 css -->
  <link rel="stylesheet" href="{% static 'user/selected/pselected.css' %}"> 
  
  <!-- DB card 선택 js  -->
  <script src="{% static 'movie/select/card.js' %}"></script>
  <!-- 메인js화면  -->
  <script src="{% static 'movie/select/dselect.js' %}"></script>
  <!-- j쿼리사용 js -->
  <script src="{% static 'jquery.min.js' %}"></script>
</head>
<body>
  <div class="backs">
    <!-- 메뉴바 -->
    <div class=header>
      <a href="/" class="logo" target="blank">
        <img src="{% static 'My project-1.png' %}" alt="일일영화 로고">
      </a>

      <div class="welcom">
      {% if user.is_authenticated %}
      {{ user.username }}님, 환영합니다.<br>
      </div>

      <div class="names">
        <a href="{% url 'user:profile' %}" class="btn"> 회원정보 </a>
        <a href="{% url 'user:logout' %}" class="btn">로그아웃</a>
      {% else %}
      <!-- <a href="{% url 'user:login' %}" class="btn">로그인하기</a> -->
      {% endif %}
      </div> 
    </div>
    
    <!-- 페이지 설명 창-->
    <div>
      <h1>장르를 선택해주세요</h1>
    </div>

    <!-- 선택한 내용 보여주기 -->
    <div class="show">
      <input class="showSelect" type="text" value="{{ selected_genre|default_if_none:'' }}" name="selected_genre" id="selected_genre" readonly>
    </div>

    <!-- 검색 창-->
    <form id="searchForm" autocomplete="off" class="box">
      <input type="text" name="searchWord" placeholder="{{ searchWord|default:'장르를 검색해주세요'|default_if_none:'' }}" />
    </form>
    
    <!-- DB 선택 테이블 css -->
    <section>
      <div class="content-list">
        <div class="slider">
          {% for list in targetbase_list %}
          <div class="item" onclick="TableGenre(this)">
            {{ list.genre }}
          </div>
          {% endfor %}
        </div>
      </div>
    </section>

    <!-- DB 페이징 기능 -->    
    <div class="pagination">
      <!-- DB 이전 페이지 -->
      {% if page_obj.has_previous %}
        <a onclick="searchFormCheck('{{ searchWord }}', {{ page_obj.previous_page_number }})" class="page-link">이전</a>
      {% else %}
        <a href="#" class="page-link" tabindex="-1" aria-disabled="true">이전</a>
      {% endif %}

      <!-- DB 페이지 리스트 -->
      {% for page_number in page_obj.paginator.page_range %}
        {% if page_number >= page_obj.number|add:-5 and page_number <= page_obj.number|add:5 %}
          {% if page_number == page_obj.number %}
            <a onclick="searchFormCheck('{{ searchWord }}', {{ page_number }});" class="page-link">{{ page_number }}</a>
          {% else %}
            <a onclick="searchFormCheck('{{ searchWord }}', {{ page_number }});" class="page-link">{{ page_number }}</a>
          {% endif %}
        {% endif %}
      {% endfor %}

      <!-- DB 다음페이지 -->
      {% if page_obj.has_next %}
        <a onclick="searchFormCheck('{{ searchWord }}', {{ page_obj.next_page_number }});" class="page-link">다음</a>
      {% else %}
        <a href="#" tabindex="-1" aria-disabled="true" class="page-link">다음</a>
      {% endif %}
    </div>
    
    <!-- 각 HTML로 이동 버튼 -->
    <div class="page_2">
      <a href="{% url 'movie:board1' %}" class="btn_before">이전(1/4)</a>
      <a href="javascript:void(0);" class="btn_next" onclick="selectDataGenre();">다음(3/4)</a>
    </div>
    
    <form id="pageForm">
      <input type="hidden" name="searchWord" id="searchWord">
      <input type="hidden" name="page" id="page">
      <input type="hidden" name="selected_genre" id="genre" value="{{ selected_genre|default_if_none:'' }}">
    </form>
  </div>
</body>
{% comment %}
<script src="{% static 'common/session.js' %}"></script>
{% endcomment %}
  
</html>

<form action="{% url 'movie:board2to3' %}" method="get" id="selectedGenreForm">
  <input type="hidden" name="genre" id="selected_genre_hidden_input">
</form>