box_office/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views # 이메일로 비밀번호 재설정의 위한 import
# from restFrameWork import views
# from  restFrameWork import views 

# # 5-1. RestTemplate and FASTAPI
# from django.contrib.auth.models import User # Django를 Client를 만들기위한, api-auth를 위한 Django 내장 User 객체 import하기 
# from rest_framework import routers, serializers, viewsets   # 먼지는 모르겠지만 Django REST framework 사이트를 따라가면서 import하기

# # 5-2. Serializers define the API representation # import한 Serializers 모듈로 API대표자대리인표현을 정의하기
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         Model = User
#         fields = ['url', 'username', 'email', 'is_staff']

# # 5-3. ViewSets 모듈로 view의 behavior을 정의하기
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer

# # 5-4. Routers가 자동으로 쉽게 환경설정배열(configuration) 결정할수 있도록 제공한다
# router = routers.DefaultRouter()
# router.register(r'users', views.UserViewSet)   #처음보는것 f''String같은거  r'' -> RawString ESCAPE문법을 ESCAPE하지못하도록 제어
# router.register(r'groups', views.GroupViewSet)

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', TemplateView.as_view(template_name='common/home.html'), name='home'),
    path("movie/", include("movie.urls")),
    path("user/", include("user.urls")),
    # path('password/', include('django.contrib.auth.urls')),

    # 비밀번호 재설정 토큰관련 url
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='account/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),

    # api-auth RestTemplate를 위한 root url 설정
    # 6. 우리의 API객체를 자동으로 URL을 전달하고, 우리는 추가적으로 브라우저 API를 위한 로그인 URL들을 include
    # path('api-auth/', include('restFrameWork.urls', namespace='restFrameWork')),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

user/urls.py
from django.urls import path
from . import views
# from user.views import kakaoSignInView, kakaoCallbackView
from django.contrib.auth import views as auth_views
from rest_framework_simplejwt.views import TokenRefreshView
app_name = 'user'
urlpatterns = [
    # path('login/',auth_views.LoginView.as_view(template_name = 'dist/index.html', next_page = 'movie:board1'),name='login'),
        # django.contrib.auth.views를 import하여 내장 LoginView를 사용하는 url
        # dist/index.html은 로그인기능과 회원가입기능이 같이있는 템플릿
    path('join/', views.UserCreateForm.as_view(),name='join'),
        # 회원가입기능의 ClassView와 관련된 url
    # path('join/', views.UserCreateForm.as_view(),name='join'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('login/',auth_views.LoginView.as_view(template_name = 'dist/index.html', next_page = '/'),name='login'), 
    # path('login/', views.LoginClassView.as_view(), name='login'),

    path('logout/',auth_views.LogoutView.as_view(next_page = '/'),name='logout'),
        # django.contrib.auth.views를 import하여 내장 LogoutView를 사용하는 url
        # 로그아웃 후 이전페이지인 / 로 이동

    path('profile/', views.profile, name='profile'),
        # 프로파일페이지와 관련된 뷰와 연결해주는 url
    path('profile/selected/', views.UserSelectedDataView.as_view(), name='selected_data'),
    
    path('delete_user_page/', views.delete_user_page, name='delete_user_page'),
        # 회원탈퇴페이지와 관련된 뷰와 연결해주는 url
    path('delete_user/', views.delete_user, name='delete_user'),
        # 새로이 만들고자하는 회원탈퇴url

    path('password_check_ajax/', views.password_check_ajax, name='password_check_ajax'),
    # 비밀번호 변경시 현재의 비밀번호와 동일한 비밀번호로 변경하지 못하도록 하는 비밀번호 체크 ajax 함수

    path('change_user_page/', views.userchangepage ,name='change_user_page'),
        # 회원정보수정페이지와 관련된 뷰와 연결해주는 url
    path('change_user/', views.userchangeview ,name='change_user'),
    # path('<int:auth_user_id>/change_user/', views.userchangeview ,name='change_user'),
        # 회원정보수정기능과 관련된 뷰와 연결해주는 url
    
    path('ajax_user_login/', views.ajax_user_login, name='ajax_user_login'),
        # 로그인 관련 ajax view함수  

    path('ajax_user_signup/', views.ajax_user_signup, name='ajax_user_signup'),
        # 회원가입 관련 ajax view함수

    ####### 주석기준 위 url 사용중인 url / 아래 비사용 혹은 테스트중인 url
    
    # 
    # path('constitution_email/', views.constitution_email, name='constitution_email'),
        # 영화사 이메일 등록관련 view함수

    path('ajax_confirm_email/', views.ajax_confirm_email, name='ajax_confirm_email'),
        # 영화사 이메일 확인관련 ajax view함수

    path('delete_user/', views.delete_user, name='delete_user'), ## 원래사용하던 회원탈퇴url
        # 회원탈퇴기능과 관련된 뷰와 연결해주는 url
    # path('login/', views.LoginClassView.as_view(), name='login'),

    #######
    # 비밀번호 재설정 토큰관련 url
    path('password_reset/', views.password_reset_request, name="password_reset"),

    # # 원본 이메일 보내기 
    path('ajax_token_email/', views.ajax_token_email, name="ajax_token_email"),

    # # 테스트용 이메일 보내기
    # path('ajax_token_email/', views.AjaxTokenEmail, name='ajax_token_email'),
    #     # 영화사 이메일 확인관련 ajax view함수

    # 이메일에서 클릭하라는 부분 클릭시 데이터를 받아내는 url 그 받은데이터를 activate view에 전달을 한다
    path('activate/<str:uidb64>/<str:token>/<str:targetemail>', views.activate, name="activate"),

    path('ajax_to_find_confirm_email/', views.ajax_to_find_confirm_email, name="ajax_to_find_confirm_email"),


    path('findpasswordreset/', views.findpasswordreset, name="findpasswordreset"),
    path('emailresetpassword/<str:username>/<str:targetemail>', views.emailresetpassword, name="emailresetpassword"),

    
    path('fromeamilpasswordreset/', views.fromeamilpasswordreset, name='fromeamilpasswordreset'),


    path('toresetpasswordfindemail/', views.toresetpasswordfindemail, name='toresetpasswordfindemail'),

    path('toresetpasswordcheckpassword/', views.toresetpasswordcheckpassword, name='toresetpasswordcheckpassword'),
    
    #탈퇴하기 직전 탈퇴의 이유를 가지고 view로 가는 url
    path('delete_user_reason/', views.delete_user_reason, name='delete_user_reason'),


    # 실패
    # 카카오 로그인 요청에 대한 코드 
    # path('login_user_kakao', views.login_user_kakao, name='login_user_kakao'),
    # 다녀오고나서 데이터를 가지고 redirect될 url과 View
    # path('login_user_kakao_callback', kakaoCallbackView.as_view(), name='login_user_kakao_callback'),
    

    
]

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.hashers import check_password
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model


class CheckPasswordForm(forms.Form):
    password = forms.CharField(label='비밀번호', widget=forms.PasswordInput(
        attrs={'class': 'form-control',}), 
    )
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = self.user.password
        
        if password:
            if not check_password(password, confirm_password):
                self.add_error('password', '비밀번호가 일치하지 않습니다.')


# forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model

class CustommUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name')

user/views.py
from django.http import Http404, JsonResponse
from django.shortcuts import  redirect, render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth import forms as auth_forms
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST#, require_http_methods
from .forms import CheckPasswordForm, CustommUserChangeForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.models import AbstractUser
from django.views import View
from django.shortcuts import get_object_or_404
from django.contrib.auth.views import LoginView
from movie.models import SelectedBase
from django.contrib import messages
from user.decorators import * # 함수형 뷰 데코
from django.utils.decorators import method_decorator # 클래스기반뷰에사용 데코
from json import loads
from django.contrib.auth.hashers import check_password
import json
import smtplib
from email.mime.text import MIMEText
from django.contrib.auth.hashers import check_password
from rest_framework import HTTP_HEADER_ENCODING

## Session import하기위한 코드
from django.contrib.sessions.models import Session

## KaKaoLogin API import 실패한 장고 KaKao API 관련 라이브러리 import 하는 코드들
## pip list에서 requests 없고 dotenv없음 pip list에서 다운해야함 dotenv는 dotenv가 아니라 python-dotenv pip install해야함
# import requests
# from dotenv import load_dotenv
# import json
# import os  #실패
## 시도 django-allauth
## Settings에 선언한 변수명가져오기
# from django.conf import settings


## SMTP 관련 인증
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_str #,django 4버젼 미만force_text
from .tokens import account_activation_token


## 비밀번호 재설정 토큰관련 모듈
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail, BadHeaderError
from django.db.models.query_utils import Q
from django.http import HttpResponse
# from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode


# 비밀번호 재설정 토큰관련 함수뷰
def password_reset_request(request):
            # request.
            # if (auth_views.UserModel.objects.filter(id=pk)):
                    if request.method == "POST":
                        password_reset_form = PasswordResetForm(request.POST)
                        if password_reset_form.is_valid():
                            data = password_reset_form.cleaned_data['email']
                            associated_users = get_user_model().objects.filter(Q(email=data))
                            if associated_users.exists():
                                for user in associated_users:
                                    subject = '[일일영화] 비밀번호 재설정'
                                    email_template_name = "account/password_reset_email.txt"
                                    c = {
                                        "email": user.email,
                                        'domain': settings.HOSTNAME,
                                        'site_name': 'givwang',
                                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                                        "user": user,
                                        'token': default_token_generator.make_token(user),
                                        'protocol': settings.PROTOCOL,
                                    }
                                    email = render_to_string(email_template_name, c)
                                    try:
                                        send_mail(subject, email, 'dailydailymovie@gmail.com' , [user.email], fail_silently=False)
                                    except BadHeaderError:
                                        return HttpResponse('Invalid header found.')
                                    return redirect("/password_reset/done/")
                    password_reset_form = PasswordResetForm()
                    return render(
                        request=request,
                        template_name='account/password_reset.html',
                        context={'password_reset_form': password_reset_form})
            # else:
            #     return 


class UserCreateForm(generic.CreateView):
    """ django.views.generic.CreateView 내장뷰를 상속받는 회원가입관련 클래스 뷰"""
    form_class = auth_forms.UserCreationForm # django.contib.auth.forms.UserCreationForm 내장폼을 form_class 변수명에 지정
    template_name = 'dist/index.html' # get 방식일 경우 회원가입유도
    success_url = reverse_lazy('user:login') # post 방식일 경우 리다이렉트로 로그인으로 가는상황


class UserLoginView(LoginView):
    template_name = 'dist/index.html'  #가입하기템플릿으로 가라.

    def form_invalid(self, form):
        messages.error(self.request, '로그인에 실패하였습니다.', extra_tags='danger')
        return super().form_invalid(form)


# 유저가 선택한 데이터가 있는 게시판을 만들기 위한 view
class UserSelectedDataView(generic.ListView):
    paginate_by = 12
    template_name = 'user/user_selected_data.html'
    context_object_name = "selecteddata_list"

    def get_queryset(self):
        
        result = SelectedBase.objects.order_by('-id').filter(writer_id=self.request.user)
        return result
    
URL_LOGIN = '/user/login/'

@login_required(login_url=reverse_lazy('user:login'))
def profile(request):
    """
    프로파일과 관련된 html으로 render하는 함수뷰,
    login_required 데코레이션을 사용하여 로그인이 되어있지 않을경우,
    reverse_lazy 로 user:login로 로그인유도."""
    return render(request, 'user/profile.html')

def delete_user_page(request):
    """
    회원탈퇴 관련된 html으로 render하는 함수뷰,
    login_required 데코레이션을 사용하여 로그인이 되어있지 않을경우,
    reverse_lazy 로 user:login로 로그인유도."""
    return render(request, 'user/user_delete.html')

def userchangepage(request):
    """
    회원정보수정과 관련된 html으로 render하는 함수뷰,
    login_required 데코레이션을 사용하여 로그인이 되어있지 않을경우,
    reverse_lazy 로 user:login로 로그인유도."""
    return render(request, "user/user_change_page.html")

@login_required(login_url=reverse_lazy('user:login'))
def  userchangeview(request):
    """
    회원정보수정 기능과 관련된 함수 뷰이며
    현재 뷰 그리고 현재 뷰로 오도록한 url 그리고 url로 오도록한
    html template의 내의 urltemplates가 적힌  form에서 보내는 name을 활용
    """
    # auth_user.username 테이블 필드명 
    # username = request.POST.get('username', '') ## form에서 POST 형식으로 보낸 name명인 username을 get 해서 username이라는 변수명에 초기화 
    username = request.user.username
    auth_user_id=request.user.id
    password = request.POST.get('password', '') ## form에서 POST 형식으로 보낸 name명인 password을 get 해서 username이라는 변수명에 초기화 
    password2 = request.POST.get('password2', '') ## form에서 POST 형식으로 보낸 name명인 password2을 get 해서 username이라는 변수명에 초기화 
    try:
        if username == request.user.username and password == password2:
            user = auth_views.UserModel.objects.get(pk=auth_user_id)
            user.set_password(password)
            user.save()

            return redirect(reverse_lazy('user:profile'))
        else:
            return redirect(reverse_lazy('user:change_user_page'))
    except:
        return redirect(reverse_lazy('user:profile'))

def password_check_ajax(request):
    id = request.user.id
    data = loads(request.body)
    wantnewpassword=data.get("changepassword1")
    user = auth_views.UserModel.objects.get(pk=id)
    
    if check_password(wantnewpassword,user.password):
        print('변경하고자하는 비밀번호가 현재 비밀번호와 일치합니다.')
        return JsonResponse({'result':'False'})
    else:
        print('변경하고자하는 비밀번호가 현재 비밀번호와 일치하지 않습니다.')
        return JsonResponse({'result':'True'})
    
# delete() 하지않고 is_active를 0으로 update()할 새로운 회원탈퇴함수뷰.
def delete_user_reason(request):
    data = loads(request.body)

    reason = data.get('reason')
    print(f'탈퇴한이유는 -> {reason}')
    
    request.session['reason'] = reason
    if reason is not None:
        return JsonResponse({'result': 'True'})
    else:
        return JsonResponse({'result': 'False'})


def delete_user(request):
    userid = request.user.id 
    if auth_views.UserModel.objects.get(pk=userid):
        reason = request.session['reason']
        print(f'reason은 : {reason}')
        auth_views.UserModel.objects.filter(pk=userid).update(is_active=False, username="",email="", first_name=reason)
        print("해당유저가 비활성화 되었습니다.")

        try:
            request.session.modified = True #세션삭제가 가능하도록 등록
            del request.session['reason']
        except:
            pass
        
        return redirect('user:join')
    else:
        print("이미 비활성화 되어있는 유저입니다.")
        return redirect('user:join')


def login(request):
    return render(request, 'dist/index.html')


############## Ajax 함수뷰
# 원본 ajax singup view 함수 제대로 되는것!!!
def ajax_user_signup(request):
    data = loads(request.body)
    ajax_username = data.get('signupname')
    
    targetuser = auth_views.UserModel.objects.filter(username=ajax_username)

    if targetuser.count() > 0:
        return JsonResponse({'result': 'False'})
    else:
        return JsonResponse({'result': 'True'})

    
# 원본 ajax login view 함수
# 자바스크립트 ajax와 연결되어 
def ajax_user_login(request):
    data = loads(request.body)
    ajax_username = data.get('loginname')
    ajax_password = data.get('loginpassword')

    targetuser = auth_views.UserModel.objects.filter(username=ajax_username)
    if targetuser.count() > 0:
        return JsonResponse({'result': 'True'})
    else:
        return JsonResponse({'result': 'False'})


################ 이메일 자바스크립트Ajax관련 함수뷰 
################ 이메일관련 함수뷰

# 자바스크립트 ajax와 연결되어 유저의 email 컬럼에 데이터가 존재하는지 여부를 확인하는 함수뷰
def ajax_confirm_email(request):
    user_id = request.user.id

templates/user/activation_email.html
안녕하세요? {{user.username}}님, 아래 링크를 클릭하여 영화사 이메일등록을 해주세요:
http://{{domain}}{% url 'user:activate' uid token targetemail %}

templates/user/find_id_email.html
안녕하세요? {{targetemail}}님, 
{{targetemail}} 이메일로 가입된 계정의 아이디는 {{username}}입니다.

templates/user/find_pw_emai.html
안녕하세요? {{username}}님, 아래의 링크를 클릭하여 아이디 비밀번호 재설정을 해주세요
http://{{domain}}{% url 'user:emailresetpassword' username targetemail %}

templates/user/login_user_kakao.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  카카오로그인
</body>
</html>

templates/user/password_reset.html
{% extends 'user/password_reset_base.html' %}

{% block content %}
  <!--Reset Password-->
  <div>
    <h2>비밀번호 재설정</h2>
  <hr>
  <p>비밀번호를 잊어버리셨나요?<br>
      가입하신 이메일을 입력해 주세요.<br>
      잠시 후 해당 이메일로 비밀번호 재설정 메일이 발송됩니다.</p>
    <form method="POST">
        {% csrf_token %}
        {{ password_reset_form }}
        <button type="submit">전송</button>
    </form>
  </div>
{% endblock %}

templates/user/password_reset_head.html
<head>
  <meta charset="UTF-8">
  <title>Givwang</title>
</head>

templates/user/profile.html
{% load static %}
<title>일일영화 - 회원 정보</title>
<link rel="stylesheet" href="{% static 'user/infos/profile.css' %}">
<link rel="stylesheet" href="{% static 'common/home/menubar.css' %}">

<body>
  <div class=container>
    <!-- 메뉴바 -->
    <div class=header>
      <a href="/" class="logo" target="blank">
        <img src="{% static 'My project-1.png' %}" alt="일일영화 로고">
      </a>

      <div class="welcom">
      {% if user.is_authenticated %}
      {{ user.username }}님, 환영합니다.<br>
      </div>

      <div class="names">
        <a href="{% url 'home' %}" class="btn"> 홈으로 </a>
        <a href="{% url 'user:logout' %}" class="btn">로그아웃</a>
      {% endif %}
      </div> 
    </div>

    <div class="container2">
      <!-- 비밀번호 변경 카드-->
      <div class="box">
        <h3>비밀번호 변경</h3>
        <p>
          비밀번호를 변경 하시겠습니까?
          <br><br><br>
        </p>
        <a href="{% url 'user:change_user_page' %}"><button>비밀번호 변경</button></a>
        <span class="count">1</span>
      </div>

      <!-- 회원탈퇴 카드 -->
      <div class="box">
        <h3>회원탈퇴</h3>
        <p>
          탈퇴하시면 회원정보가 <br>즉시 삭제됩니다.<br>삭제하러 가시겠습니까?
        
        </p>
        <a href="{% url 'user:delete_user_page' %}"><button>회원탈퇴</button></a> 
        <span class="count">2</span>
      </div>

      <!-- 회원데이터 카드-->
      <div class="box">
        <h3>자료실</h3>
        <p>
          선택하신 내용들을 모두 <br> 볼 수 있습니다.<br>자료들을 확인하러 가시겠습니까?
        </p>
        <a href="{% url 'user:selected_data' %}"><button>자료실</button></a>
        <span class="count">3</span>
      </div>
    </div>
  </div>
</body>

templates/user/user_change_page.html
{% load static %}
<title>일일영화 - 비밀번호 변경</title>
<script src="{% static 'user/change/script.js' %}"></script>
<link rel="stylesheet" href="{% static 'user/change/modify.css' %}">
<link rel="stylesheet" href="{% static 'common/home/menubar.css' %}">
<link rel="icon" type="image/png" sizes="32x32" href="../../static/film-slate.png">
<!-- j쿼리사용 js -->
<script src="{% static 'jquery.min.js' %}"></script>  

<!-- <body onload="noBack();" onpageshow="if(event.persisted) noBack();" onunload=""> -->
<body>

  <!-- 메뉴바 -->
  <div class=header>
    <a href="/" class="logo" target="blank">
      <img src="{% static 'My project-1.png' %}" alt="일일영화 로고">
    </a>

    <div class="welcom">
    {% if user.is_authenticated %}
    {{ user.username }}님, 환영합니다.<br>
    </div>

    <div class="names">
      <a href="{% url 'user:profile' %}" class="btn"> 회원정보 </a>
      <a href="{% url 'user:logout' %}" class="btn">로그아웃</a>
    {% else %}
    <!-- <a href="{% url 'user:login' %}" class="btn">로그인하기</a> -->
    {% endif %}
    </div> 
  </div>

  <!-- 본 내용 -->
  <input type="hidden"  id="originName" value="{{ user.username }}">
  <input type="hidden" id="csrf_token" value="{{ csrf_token }}">

  
  <table>
    {% comment %}
    <form action="{% url 'user:change_user' %}" id="userChange" method="post" novalidate onsubmit="return changeFormIdCheckMent();">
    <form action="{% url 'user:change_user' %}" id="userChange" method="post">
    {% endcomment %}
    <div class="box">
      <span class="text-center">비밀번호 수정</span>
      <form action="{% url 'user:change_user' %}" id="userChange" method="post" onsubmit="return false">
      {% comment %}
      <form action="{% url 'user:change_user' auth_user_id=user.id %}" id="userChange" method="post" onsubmit="return false"></form>  
      {% endcomment %}
        {% csrf_token %}

        <!-- <div class="input-container">
          <span class="name-id">아이디</span>
          <input type="text" name="username" value="{{ user.username }}" id="changeName" readonly>
          <input type="hidden" id="originName" value="{{ user.username }}">
        </div> -->
        <div class="inputBox">		
          <input type="password" name="password" id="changePassword1" required=""/>
          <span>비밀번호</span>
        </div>
        <br>
        <div class="inputBox">		
          <input type="password" name="password2" id="changePassword2" required=""/>
          <span>비밀번호 재입력</span>
        </div>
          <button type="submit" name="change_user_bt" class="mbtn" onclick="changeFormIdCheckMent();">수정하기</button>
          {% comment %}<button type="submit" name="change_user_bt" class="mbtn" onclick="changeFormIdCheckMent();">수정하기</button>{% endcomment %}
      </form>
    </div>
  </table>  
  
</body>

templates/user/user_delete.html
{% load static %}
<title>일일영화 - 회원탈퇴</title>
<script src="{% static 'jquery.min.js' %}"></script>
<script src="{% static 'user/delete/script.js' %}"></script>
<link rel="stylesheet" href="{% static 'common/home/welcome.css' %}">
<link rel="stylesheet" href="{% static 'common/home/menubar.css' %}">
<link rel="stylesheet" href="{% static 'user/delete/remove.css' %}">
<link rel="icon" type="image/png" sizes="32x32" href="../../static/film-slate.png">

<body onload="noBack();" onpageshow="if(event.persisted) noBack();" onunload="">
  <input type="hidden" id="csrf_token" value="{{ csrf_token }}"> 
  <!-- 메뉴바 -->
  <div class=header>
    <a href="/" class="logo" target="blank">
      <img src="{% static 'My project-1.png' %}" alt="일일영화 로고">
    </a>

    <div class="welcom">
    {% if user.is_authenticated %}
    {{ user.username }}님, 환영합니다.<br>
    </div>

    <div class="names">
      <a href="{% url 'user:profile' %}" class="btn"> 회원정보 </a>
      <a href="{% url 'user:logout' %}" class="btn">로그아웃</a>
    {% else %}
    <!-- <a href="{% url 'user:login' %}" class="btn">로그인하기</a> -->
    {% endif %}
    </div> 
  </div>

  <!-- 템플릿 주내용 -->
  <table>
    <div class="content">

      <!-- comment가 원본임 -->
      {% comment %}
      <form action="{% url 'user:delete_user' %}" method="post" novalidate onsubmit="return deleteFormCheckMent();">
      {% endcomment %}
        <form action="{% url 'user:delete_user_reason' %}" method="post">
        {% csrf_token %}

        <h3>
          삭제 버튼을 누르시면 완전히 삭제가 되어 되돌릴 수 없습니다.<br><br>
          {{ user.username }} 회원님의 계정을 삭제 하시겠습니까?<br>
        </h3>

    </div>
        <!-- comment가 원본임 -->
        {% comment %}
        <button type="submit" name="delete_user_bt" id="deleteUserBt" class="btn o">확인</button>
        {% endcomment %}
        
        <!-- 설문조사용 테스즈 전용 모달창 -->
        <div id="my_modal">
          <label><input type="radio" name="reason" id="reason" value="개인정보 떄문에" >개인정보 때문에</label><br>
          <label></label><input type="radio" name="reason" id="reason" value="재미가 없어서">재미가 없어서</label><br>
          <label></label><input type="radio" name="reason" id="reason" value="이유없음">이유없음</label><br>
          <input type="button" id="button" onclick="reasonAjax()" value="제출하기"></button>
          <a class="modal_close_btn">돌아가기</a>
        </div>
        <button type="button" name="delete_user_bt" id="deleteUserBt" class="btn o" onclick="questionModal();">확인</button>
      </form>
        <button type="submit" class="btn x" onclick="info_user()">취소</button>        
  </table>        
</body>